### PR TITLE
Upgrade to Gradle 6.0 and Java 11

### PR DESCRIPTION
**Pull request by riy**
Hey Jens,

I did the bare minimum to make Degraph work with Java 11, which was upgrading Gradle to a 5.x (here: `5.6.2`), and along the way I removed the Java 8 tests. I'm not much of a Scala buff, so you might want to take a closer look at this.

The library is already happily used by some teams at Kühne + Nagel, so having the pull request (reviewed and) accepted would make our week.

Thanks & thank you for the great work on Degraph! :-)

**EDIT 2019-11-18:** it's Gradle 6.0 now.

### CODE REVIEW

**Comment by riy** [comment]
@schauder The shippable checks are failing because the Shippable image that is configured for this repository installs Java 7, which doesn't fly with Gradle 5.6.2. If possible please update to a newer image. Danke Dir! :-)

**Comment by schauder** [comment]
I no longer find the time to maintain this library. If you or anyone else is interested in picking it up I'd be happy to pass it on.

**Comment by riy** [comment]
Alright, I'm in.
Not sure how a transfer works in regard to new releases, but I guess since `de.schauderhaft` is associated with your account on Maven Central I'd have to re-release it under different coordinates. Please let me know if that's ok with you or if you have a better suggestion.

**Comment by schauder** [comment]
That's great news.

Yes to new maven coordinates. 

Do you want to chat about what (in my opinion) should happen with the project?

**Comment by riy** [comment]
Yes, absolutely. Chatting in here, on the phone (I'm located in Germany), via e-mail or Telegram?

**Comment by schauder** [comment]
Let's do a Hangout or similar in the week starting on the 14th of October until then let's switch to e-mail (jens at schauderhaft dot de)

**Comment by riy** [comment]
A quick update:

I've brought the `jdk8tests` back and everything compiles and is nice and dandy, but it's not set up as intended. I had to set this module's `targetCompatibility` to `11` to make the build work, due to a change that was introduced in Gradle 5.3+.

This is due to...
```groovy
dependencies {
    compile project(':core')
...
```
... which it can't load because `:core` is compiled with a `targetCompatibility` of `11` while `jdk8tests` should be `1.8`.

If I understand the `jdk8tests` module correctly then it's purpose is to utilize ASM and run the tests through it. If its generated bytecode is that of Java 11 (just so the JDK 11-compiled `:code` dependency can be used) then the purpose of the `jdk8tests` module is defeated.

Am I understanding this correctly? Do you have an advice for me, @obecker?

**Comment by schauder** [comment]
The purpose of the `jdk8test` is to test that Degraph handles Java 8 code correctly, mainly lambdas and annotations in new places.

It should be completely fine to compile it with a higher compiler version or a higher byte code target version then 8.

Just a lower version won't work obviously.

**Comment by riy** [comment]
Thanks for the explanation. I guess my limited Scala knowledge made me misunderstand the purpose of `AnalyzerTest.scala`. I saw the `asm.Analyzer.analyze(...)` commands in there and assumed a correlation between the generated bytecode and what it's testing for.

I'll wrap this up soon. Thanks again!

**Comment by schauder** [comment]
Well there is the possibility that the byte code generated by JDK11 and JDK8 differs in a way that it gets reported differently by asm and Degraph therefore works with one but not the other. But that would be 

a) a bug in ASM and or the JDK
b) a risk we should take.

**Comment by riy** [comment]
I've pushed a release that properly builds on Shippable. The `shippable.yml` format has changed, took me a few tries to make it work. Also, specifying `language: scala` has been removed as, in conjunction with an empty `build > ci` node, this would just trigger `sbt` as the build tool etc.. We're not making use of any of that. Instead we're now more or less plain vanilla in regard to the Shippable build.

Please have a look, also @obecker, and let me know your thoughts. Thanks!

**Comment by obecker** [comment]
@riy Looks good to me

**Comment by riy** [comment]
Yes, I don't see a reason why we _have_ to set the `targetCompatibility` to `11`. Leaving both parameters on `1.8` and just compiling it with Java 11 should suffice as long as degraph is not using Java 11 language features. I ran a few quick tests on our code (using JDK 8 and 11) and all is well.
The latest commit contains the change. Please have another look and let me know what you think.

**Pull request merged**
